// Auth
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'

// Breadcrumb
export const ADD_CHILD_BREADCRUMB = 'ADD_CHILD_BREADCRUMB'
export const UPDATE_BREADCRUMB = 'UPDATE_BREADCRUMB'

// User
export const GET_LOGGED_USER = 'GET_LOGGED_USER'
export const GET_USERS_BY_CLIENTID = 'GET_USERS_BY_CLIENTID'
export const REMOVE_LOGGED_USER = 'REMOVE_LOGGED_USER'

// DataHub
export const GET_DATA_HUB = 'GET_DATA_HUB'
export const RETRIEVE_DATA_TYPE = 'RETRIEVE_DATE_TYPE'
export const DELETE_DATA_TYPE = 'DELETE_DATA_TYPE'
export const SAVE_DATA_TYPE = 'SAVE_DATA_TYPE'
export const SET_CATE_ITEM = 'SET_CATE_ITEM'

export const INSERT_CATE_ITEM_BY_CLIENT = 'INSERT_CATE_ITEM'
export const UPDATE_CATE_ITEM_BY_CLIENT = 'UPDATE_CATE_ITEM'
export const SAVE_CATE_ITEM_BY_CLIENT = 'SAVE_CATE_ITEM_BY_CLIENT'
export const UPDATE_DATA_HUB_LOADING = 'UPDATE_DATA_HUB_LOADING'
export const GET_DATA_HUB_BY_CLIENT = 'GET_DATA_HUB_BY_CLIENT'

// Address
export const GET_CITY_LIST = 'GET_CITY_LIST'
export const GET_DISTRICT_LIST = 'GET_DISTRICT_LIST'
export const GET_WARD_LIST = 'GET_WARD_LIST'
export const UPDATE_CITY_LIST = 'UPDATE_CITY_LIST'
export const UPDATE_DISTRICT_LIST = 'UPDATE_DISTRICT_LIST'
export const UPDATE_WARD_LIST = 'UPDATE_WARD_LIST'

// Influencer
export const INVITE_INFLUENCER = 'INVITE_INFLUENCER'
export const GET_INFLUENCER = 'GET_INFLUENCER'
export const UPDATE_INFLUENCER = 'UPDATE_INFLUENCER'
export const UPDATE_STATUS_INFLUENCER = 'UPDATE_STATUS_INFLUENCER'
export const DELETE_INFLUENCER = 'DELETE_INFLUENCER'
export const GET_LIST_INFLUENCER = 'GET_LIST_INFLUENCER'
export const GET_SOCIALS_INFLUENCER = 'GET_SOCIALS_INFLUENCER'
export const GET_SOCIALS_POST = 'GET_SOCIALS_POST'

// File
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const GET_FILE = 'GET_FILE'

// Campaign
export const GET_CAMPAIGN = 'GET_CAMPAIGN'
export const GET_LIST_CAMPAIGN = 'GET_LIST_CAMPAIGN'
export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN'
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN'
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN'
export const SEARCH_CAMPAIGN = 'SEARCH_CAMPAIGN'
export const GET_CAMPAIGN_INFLUENCERS = 'GET_CAMPAIGN_INFLUENCERS'
export const GET_ALL_CAMPAIGN_INFLUENCERS = 'GET_ALL_CAMPAIGN_INFLUENCERS'

// Toast
export const MAKE_TOAST = 'MAKE_TOAST'

// Report
export const RETRIEVE_REPORTS = 'RETRIEVE_REPORTS'
export const SET_REPORT_DETAIL = 'SET_REPORT_DETAIL'
export const CREATE_REPORT = 'CREATE_REPORT'
export const REMOVE_REPORT = 'REMOVE_REPORT'

// Utils
export const API_DATA_PENDING = 'API_DATA_PENDING'
export const API_DATA_SUCCESS = 'API_DATA_SUCCESS'
export const API_DATA_FAILURE = 'API_DATA_FAILURE'
export const API_DATA_RESET = 'API_DATA_RESET'

// Clients
export const RETRIEVE_CLIENTS = 'RETRIEVE_CLIENTS'
export const ADD_CLIENT = 'ADD_CLIENT'
export const CREATE_CLIENT = 'CREATE_CLIENT'
export const REMOVE_CLIENT = 'REMOVE_CLIENT'
export const SET_CLIENT_DETAIL = 'SET_CLIENT_DETAIL'
export const RETRIVE_CLIENT_STAFFS = 'RETRIVE_CLIENT_STAFFS'
export const ADD_CLIENT_STAFF = 'ADD_CLIENT_STAFF'
export const GENERATE_CLIENT_ID = 'GENERATE_CLIENT_ID'
export const UPDATE_CLIENT_STAFF = 'UPDATE_CLIENT_STAFF'
export const GET_CLIENT_REPORTS = 'GET_CLIENT_REPORTS'
export const GET_CLIENT_CAMPAIGNS = 'GET_CLIENT_CAMPAIGNS'
export const GET_CLIENT_INFLUENCERS = 'GET_CLIENT_INFLUENCERS'
export const UPDATE_CLIENT_ADMIN_ROLE = 'UPDATE_CLIENT_ADMIN_ROLE'

// Roles
export const RETRIEVE_ROLES = 'RETRIEVE_ROLES'
export const ADD_NEW_ROLE = 'ADD_NEW_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'
export const RETRIEVE_PERMISSIONS = 'RETRIEVE_PERMISSIONS'
